#-------------------------------
# General Site Settings
title: Top拓璞補習班
logo: index.jpg # You can add own logo.
description: Top拓樸補習班


#------------------------------
# Author Settings
author:
  name: Top拓樸補習班
  image: index.jpg
  say-hello: <strong>全國最強最犀利的專業升大學家教班</strong>
  bio: 創立38年，原為北車站前大班，並獲兩位前總統(陳水扁、馬英九)及日本NHK、歐洲和荷蘭電視台到班訪問，特在天母地區開設精緻小班，並贏得天中、蘭雅、士林、明德等校35位以上老師及三位校務主任及成功高中校長信賴，皆將其寶貴子女託付本班，師資經驗超過25年的全國名師，一對一個別輔導、免費自習教室，讓您孩子的課業倍受呵護。


#-------------------------------
# Contact links
facebook: https://www.facebook.com/TOP0932316668?mibextid=LQQJ4d&mibextid=LQQJ4d # Add your Facebook handle
instagram: https://instagram.com/ # Add your Instagram handle
line: https://line.me/ti/p/20040706ccc




